/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_appsync_graphqlEndpoint": "https://465hmcknpjcfxecvl6ykuaruri.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-ilei6noy4rhjlg5g6ees673tai",
    "aws_cognito_identity_pool_id": "us-east-1:78c0e6e6-10da-4ac5-b365-3a47f672b35c",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_vtv1vajq5",
    "aws_user_pools_web_client_id": "4e913aehas6n802mdp9412usm1",
    "oauth": {}
};


export default awsmobile;
